apiVersion: v1
kind: ConfigMap
metadata:
  name: notehub-config
  namespace: notehub
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "notehub"
  DB_USER: "notehub"
  LOG_LEVEL: "info"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  NOTES_SERVICE_URL: "http://notes-service:3002"
