apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notehub-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - notehub
  selector:
    matchLabels: {}
  endpoints:
    - path: /metrics
      port: http
      interval: 30s
